apiVersion: v1
kind: Service
metadata:
  name: upgrad-capstone-demo
  namespace: demo
  labels:
    helm.sh/chart: upgrad-capstone-demo-0.1.0
    app.kubernetes.io/name: upgrad-capstone-demo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: upgrad-capstone-demo